# deploy-pipeline.yaml
# - Dev → Staging → Production 단계별 배포 파이프라인 템플릿
# - 실제 구현은 .github/workflows/deploy-pipeline.yml 을 참고

name: Deploy Agent

on:
  push:
    branches: [main]
    paths:
      - 'agents/**'
      - 'infrastructure/**'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - staging
          - production

env:
  PYTHON_VERSION: '3.11'

jobs:
  deploy-dev:
    # Job 1: 개발(Dev) 환경 배포
    name: Deploy to Development
    environment: development
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Configure AWS credentials    # AWS 자격 증명 설정
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Download Artifacts          # Build 파이프라인에서 생성된 아티팩트 다운로드
        uses: actions/download-artifact@v3
        with:
          name: agent-artifacts
          path: build/

      - name: Deploy to Dev               # Dev 환경으로 Agent 배포
        run: |
          for agent_dir in agents/*/; do
            agent_name=$(basename "$agent_dir")
            echo "Deploying agent: $agent_name to dev"
            python scripts/deploy-agent.py \
              --environment dev \
              --agent-definition "$agent_dir/agent-definition.yaml"
          done
      
      - name: Sync Knowledge Base         # Dev KB 인덱스 동기화
        run: |
          python scripts/sync-knowledge-base.py \
            --environment dev \
            --agent-definition agents/customer-support-agent/agent-definition.yaml
      
      - name: Run Smoke Tests             # 기본 헬스 체크
        run: |
          python scripts/smoke-tests.py --environment dev
        continue-on-error: true

  deploy-staging:
    # Job 2: Staging 환경 배포 (운영과 유사 환경에서 최종 검증)
    name: Deploy to Staging
    environment: staging
    runs-on: ubuntu-latest
    needs: deploy-dev
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: agent-artifacts
          path: build/

      - name: Deploy to Staging
        run: |
          for agent_dir in agents/*/; do
            agent_name=$(basename "$agent_dir")
            echo "Deploying agent: $agent_name to staging"
            python scripts/deploy-agent.py \
              --environment staging \
              --agent-definition "$agent_dir/agent-definition.yaml"
          done
      
      - name: Sync Knowledge Base
        run: |
          python scripts/sync-knowledge-base.py \
            --environment staging \
            --agent-definition agents/customer-support-agent/agent-definition.yaml
      
      - name: Run Full Test Suite         # Staging에서 전체 테스트 재실행
        run: |
          pytest tests/ -v

  deploy-production:
    # Job 3: 운영(Production) 환경 배포
    name: Deploy to Production
    environment: production
    runs-on: ubuntu-latest
    needs: deploy-staging
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: agent-artifacts
          path: build/

      - name: Deploy to Production        # 운영 환경으로 최종 배포 (Canary 플래그 포함)
        run: |
          for agent_dir in agents/*/; do
            agent_name=$(basename "$agent_dir")
            echo "Deploying agent: $agent_name to production"
            python scripts/deploy-agent.py \
              --environment production \
              --agent-definition "$agent_dir/agent-definition.yaml" \
              --enable-canary
          done
      
      - name: Sync Knowledge Base
        run: |
          python scripts/sync-knowledge-base.py \
            --environment production \
            --agent-definition agents/customer-support-agent/agent-definition.yaml
      
      - name: Monitor Deployment          # 배포 직후 모니터링
        run: |
          python scripts/monitor-deployment.py --timeout 300
      
      - name: Run Production Smoke Tests  # 운영 환경에서 최종 스모크 테스트
        run: |
          python scripts/smoke-tests.py --environment production
