# test-pipeline.yaml
name: Test Agent

on:
  push:
    branches: [main, develop]
    paths:
      - 'agents/**'
      - 'tests/**'
      - 'scripts/**'
  pull_request:
    branches: [main]
    paths:
      - 'agents/**'
      - 'tests/**'
      - 'scripts/**'
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.11'

jobs:
  unit-test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Unit Tests
        run: |
          pytest tests/unit/ -v --cov=scripts --cov-report=xml
      
      - name: Test Prompt Rendering
        run: |
          python scripts/test-prompt-rendering.py
      
      - name: Upload Coverage
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          fail_ci_if_error: false

  integration-test:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: unit-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Configure AWS credentials
        if: env.AWS_ACCESS_KEY_ID != ''
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy Test Environment
        run: |
          echo "Deploying test environment..."
          # 테스트 환경 배포 로직 (예: Terraform, AWS CLI 등)
          # terraform apply -auto-approve -var="environment=test"
      
      - name: Run Integration Tests
        run: |
          pytest tests/integration/ -v
        env:
          TEST_ENVIRONMENT: test
      
      - name: Cleanup Test Environment
        if: always()
        run: |
          echo "Cleaning up test environment..."
          # terraform destroy -auto-approve -var="environment=test"

  evaluation:
    name: Evaluation Tests
    runs-on: ubuntu-latest
    needs: integration-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Configure AWS credentials
        if: env.AWS_ACCESS_KEY_ID != ''
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Run Evaluation
        run: |
          for agent_dir in agents/*/; do
            agent_name=$(basename "$agent_dir")
            dataset_file="$agent_dir/tests/evaluation-dataset.json"
            if [ -f "$dataset_file" ]; then
              echo "Running evaluation for agent: $agent_name"
              python scripts/run-evaluation.py \
                --dataset "$dataset_file" \
                --agent "$agent_dir"
            fi
          done
      
      - name: Generate Evaluation Report
        run: |
          python scripts/generate-evaluation-report.py
      
      - name: Upload Evaluation Results
        uses: actions/upload-artifact@v3
        with:
          name: evaluation-results
          path: evaluation-results/
          retention-days: 30
